///Ejemplos de operadores de operacion

3+2; //5
50-10; //40
10*20;  //200
20/2;   //10

///Tambien son conocidos como operadores binarios 
///Igual podemos ocuparlos de la siguiente manera

"susana"+"Rivera";//El operador genera una concatenacion, esto quiere decir que toma los dos valores y los junta en uno y regresa un solo valor en steing
///!
!false; ///Es para negar con el caracter y son operadores unitarios 
/// Tenemos un solo operador trabajando con un solo valor

////Operadores de asignacion

var a=1;  // Asignamos el valor a la variable que ya declaramos el= --SIRVE PARA ASIGNAR VALORES
   ///Operadores de asignacion 
   3=="3"; //Comparamos 3 con un string de valor 3 para ver si es igual el valor perse
   3==="3";//Compara que sea estrictamente iguales de valor y tipo de dato

   ///Otros tipos de comparacion
   5<3; //False
   5>3;  //True
   5<=6;  //True
   5>=6;  //False
   ///Tenemos 2 operadores para validar valores
   a && b; //Para validar que ambas variables son reales
   ///En la anterior se debe cumplir la condicion de que ambas sean verdaderas y si una de las 2 no es verdadera no se puede cumplir con la funcion 
   a || b; //Si alguna de las es verdadera se puede cumplir la condicion 
   //Cualquiera de las 2 variables puede ser verdad 
   ///Caracteres que podemos usar con variables
    var edad=24;
    //Si quiero incrementar la edad por 1 hago lo siguiente
    edad ++;
    edad ++;
    //Si quiero incrementar la edad x2 
    edad +=2;
