///Vamos a aprender que tipo de valor es verdadero y que tipo de valor es falso 
//Se llaman trusthy and falsy
///Se ocupan cuando generas condiciones en Js
///Validan si es verdadero o falso para hacer cierta accion
Boolean(0); //Es un valor falso porque no tiene valores
///Valores falsos son el 0 no tenemos elementos para iniciar ejemplo un concierto con 0 personas no se puede iniciar

Boolean(null); ///Variables con valor falso seria null un ejemplo y regresa valores de null
Boolean(NaN); //Nor a Nomber es falso porque no podemos hacer algo 
Boolean(undefined);//No tenemos un valor definidio no podemos hacer algo 
Boolean(false);
Boolean("");

///Valores verdaderos

Boolean("a");// Es verdadero
Boolean(" "); //El espacio cuenta como verdadero
Boolean(1); ///Es verdadero
Boolean([]); ///Es un arreglo ya es verdadero
Boolean({}); ///Es un objeto ya es verdadero
Boolean(function(){}); //Es verdadero
Boolean(true);