40 

"susana"///guardar texto o cadena de textos 
true
false ///creado por jorge bolean
null
undefined  ///valores placeholder`
/// SON CONOCIDOS COMO VALORES PRIMITIVOS

[1,2,3]/// SIEMPRE VIENEN VALORES PRIMITIVOS EN LOS  CORCHETES Y ES CONOCIDO COMO TIPO OBJETO
{nombre:"diego"}///Valor tipo objeto se pone en corchetes

40 ///Para saber si es valor numero usamos la palabra reservada typeof
typeof 40 ///numero
typeof "hola" /// String
///conclusion en Js tenemos valores, primitivos, objetos y raros o reservados

